const jsonData =[
  {"name": "Abuela Aurora"},
  {"name": "Abuela Sara"},
  {"name": "Abuelos Beto y Susana"},
  {"name": "Abuelos Jorge y Carmen"},
  {"name": "Ahijada Agustina"},
  {"name": "Aldana Palacios"},
  {"name": "Alejandra y Alejandro"},
  {"name": "Barbara, Rosa y Agus"},
  {"name": "Ezequiel Nievviadomsky"},
  {"name": "Hermana Jazmín y Julián"},
  {"name": "Hermano Ale, Vero, Thiago y Demian"},
  {"name": "Facundo Ponce"},
  {"name": "Gustavo Schellino"},
  {"name": "Hermano Franco"},
  {"name": "Hermano Lautaro"},
  {"name": "Horacio, Andrea y Brisa"},
  {"name": "Joana Santillán"},
  {"name": "Leonardo y Karina"},
  {"name": "Mamá Patricia y Taly"},
  {"name": "Mamá Cristina, Omar y Dylan"},
  {"name": "Marcela"},
  {"name": "Mauro García"},
  {"name": "Mica y Valentin"},
  {"name": "Milena y Aylen"},
  {"name": "Mónica y Valentin"},
  {"name": "Nicolás Toledo"},
  {"name": "Nicolás y Luz"},
  {"name": "Nicolás y Ramiro"},
  {"name": "Papá Jorge y Perla"},
  {"name": "Papá David, Miriam y Bayron"},
  {"name": "Prima Belén e Isa"},
  {"name": "Prima Day y Claudia"},
  {"name": "Prima Julieta"},
  {"name": "Prima Ludmila"},
  {"name": "Prima Mica y Jony"},
  {"name": "Prima Selena"},
  {"name": "Primo Brian, Barbara, Thiago y Milena"},
  {"name": "Primo Cristian, Noha, tía Rosita"},
  {"name": "Primo Dany, Cristofher, Amy y Keyla"},
  {"name": "Primo Ese y Sele"},
  {"name": "Primo Fer, Vicky y Benja"},
  {"name": "Primo Facu"},
  {"name": "Primo Gonzalo y Nahiara"},
  {"name": "Primo Juanchy, Georgi y Pía"},
  {"name": "Primo Lucas y Cecilia"},
  {"name": "Primo Nico, Cintia y Gael"},
  {"name": "Soledad, Nicolás, Joaquín y Manuela"},
  {"name": "Tía Belén, Kenkoo, Hanna y Lara"},
  {"name": "Tía Cari y tío Mati"},
  {"name": "Tía Gaby y tío Tony"},
  {"name": "Tía Graciela y tío Julio"},
  {"name": "Tía Lili y Joaquín"},
  {"name": "Tía Lucy y tío Carlos"},
  {"name": "Tía Mari y tío Juan"},
  {"name": "Tía Marisa"},
  {"name": "Tío Javi, tía Vero, Yair, Ian y Jana"},
  {"name": "Tío Miguel"},
  {"name": "Tío Ricky, Hana, Thiago, Thiago y Santino"}
]


export default jsonData;
