const jsonData = [
  { nombre: "Abuela Aurora" },
  { nombre: "Abuela Sara" },
  { nombre: "Abuelos Beto y Susana" },
  { nombre: "Abuelos Jorge y Carmen" },
  { nombre: "Alejandra y Alejandro" },
  { nombre: "Ale, Vero, Thiago y Demian" },
  { nombre: "Barbara, Rosa y Agus" },
  { nombre: "Ezequiel Nievviadomsky" },
  { nombre: "Hermano Franco" },
  { nombre: "Gustavo Schellino" },
  { nombre: "Horacio, Andrea y Brisa" },
  { nombre: "Jaz y Julián" },
  { nombre: "Leonardo y Karina" },
  { nombre: "Mamá y Taly" },
  { nombre: "Mamá, Omar, Lauty y Dylan" },
  { nombre: "Marcela" },
  { nombre: "Mauro" },
  { nombre: "Mica y Valen" },
  { nombre: "Mile y Aylu" },
  { nombre: "Moni y Valen" },
  { nombre: "Nico Toledo" },
  { nombre: "Nico y Luz" },
  { nombre: "Nico y Ramiro" },
  { nombre: "Papá y Perla" },
  { nombre: "Papá, Miriam y Bayron" },
  { nombre: "Prima Belén e Isa" },
  { nombre: "Prima Day y Claudia" },
  { nombre: "Prima Ludmila" },
  { nombre: "Prima Mica y Jony" },
  { nombre: "Primo Brian, Barbara, Thiago y Milena" },
  { nombre: "Primo Dany, Cristofher, Amy y Keyla" },
  { nombre: "Primo Ese y Sele" },
  { nombre: "Primo Fer, Vicky y Benja" },
  { nombre: "Primo Gonzalo y Nahi" },
  { nombre: "Primo Juanchy, Georgi y Pía" },
  { nombre: "Primo Lucas y Ceci" },
  { nombre: "Primo Nico, Cintia y Gael" },
  { nombre: "Facundo Ponce" },
  { nombre: "Tía Belén, Kenkoo, Hanna y Lara" },
  { nombre: "Tía Cari, tío Mati y Sele" },
  { nombre: "Tía Gaby y tío Tony" },
  { nombre: "Tía Graciela y tío Julio" },
  { nombre: "Tía Lili, Joaquín y Agus" },
  { nombre: "Tía Lucy, tío Carlos y July" },
  { nombre: "Tía Mari y tío Juan" },
  { nombre: "Tía Marisa" },
  { nombre: "Primo Cristian, Noha, tía Rosita" },
  { nombre: "Tío Javi, tía Vero, Facu, Yair, Ian y Jana" },
  { nombre: "Tío Miguel" },
  { nombre: "Tío Ricky, Hana, Thiago, Thiago y Santino" },
];

export default jsonData;
